# Generated by Django 6.0 on 2026-01-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('sqft', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('total_amount', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='floorplans/')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(max_length=50)),
                ('length', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specification', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules/')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories/')),
                ('length', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('specification', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kitchen_shape', models.CharField(max_length=50)),
                ('unit_type', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('length', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specification', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kitchen/')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='holly.enquiry')),
            ],
        ),
    ]
