# Generated by Django 5.0.6 on 2026-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holly', '0002_alter_enquiry_id_alter_enquirydetail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
