# Generated by Django 5.0.6 on 2026-03-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holly', '0003_enquiry_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='specification',
        ),
    ]
