# Generated by Django 5.0.6 on 2026-03-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holly', '0004_remove_enquiry_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydetail',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
