# Generated by Django 5.0.1 on 2026-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holly', '0005_enquirydetail_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmodule',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
