# Generated by Django 5.0.1 on 2026-03-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holly', '0006_alter_generalmodule_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenaccessory',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='kitchenaccessory',
            name='height',
        ),
        migrations.RemoveField(
            model_name='kitchenaccessory',
            name='length',
        ),
    ]
